# Generated by Django 5.0.7 on 2024-07-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('pno', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('cls', models.CharField(max_length=50)),
            ],
        ),
    ]
